// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		double biggerHalf = 0;
		double smallerHalf = 0;
		int i = 0; 
		while (i<n){
			double randomVal = Math.random();
			if (randomVal < 0.5 ){
				smallerHalf++ ;
				i++;
	   		}
	   		else if (randomVal >= 0.5){
				biggerHalf++ ;
				i++; 
			}
		}
		double ratio = biggerHalf/smallerHalf;

		System.out.println("> 0.5: " + smallerHalf + " times");
		System.out.println("<= 0.5: " + biggerHalf + " times");
		System.out.println("Ratio:" + ratio);
	}
}
